# Tipos primitivos
n = int(input('Digite um valor :'))
print(n)
n = float(input('Digite um valor :'))
print(n)
n = bool(input('Digite um valor :'))
print(n)
n = str(input('Digite um valor :'))
print(n)
# metodos de teste de tipo
n = input('Digite algo :')
print(n.isnumeric())
n = input('Digite algo :')
print(n.isalpha())
n = input('Digite algo :')
print(n.isalnum())
n = input('Digite algo :')
print(n.isupper())